# Generated by Django 5.2.4 on 2025-08-01 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreprocessingPipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessedDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('features', models.JSONField(default=list)),
                ('original_dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.dataset')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.preprocessingpipeline')),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_type', models.CharField(choices=[('cleaning', 'Data Cleaning'), ('encoding', 'Encoding'), ('scaling', 'Scaling'), ('feature_selection', 'Feature Selection'), ('dimensionality_reduction', 'Dimensionality Reduction'), ('custom', 'Custom')], max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='preprocessingpipeline',
            name='steps',
            field=models.ManyToManyField(to='preprocessing.preprocessingstep'),
        ),
    ]
