# Generated by Django 5.2.4 on 2025-08-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevaluation',
            name='roc_curve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='modelevaluation',
            name='confusion_matrix',
            field=models.JSONField(default=dict),
        ),
    ]
